package com.mojito.test.security;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;
import com.mojito.test.utils.log;
import org.junit.jupiter.api.Test;

import java.util.Arrays;

/**
 * @author liufq
 * @since 2023-05-04 09:31:48
 */
public class SlaUpdateTest {

    @Test
    public void test() {
        String data = "1591055686506582017\t[{\"columnAlis\":\"advice\",\"templateId\":\"1557962783618682882\",\"content\":\"【模型告警】监测到内网IP【${srcAddress}】扫描主机【${destAddress}】达到${eventCount_sum}次，请确认发起扫描的IP地址是否为授权行为，对来自内网的未授权扫描器IP及时隔离处置，并及时排查是否失陷。\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"sla\",\"templateId\":\"1558005591847129090\",\"content\":\"if(JSONExtractInt(__src_detail_info, 'asset_sla') = 0, 2, toInt32(ceil(2 * 0.4 + JSONExtractInt(__src_detail_info, 'asset_sla') * 0.6)))\",\"extendColumnType\":\"EXPRESSION\"},{\"columnAlis\":\"new_alarm_name\",\"templateId\":\"\",\"content\":\"模型-主机对外部单个目标扫描\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"new_threat_severity\",\"templateId\":\"\",\"content\":\"高危\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"new_category\",\"templateId\":\"\",\"content\":\"主机对外扫描\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"rule_sla\",\"content\":\"2\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"rule_sla_weight\",\"content\":\"0.4\",\"extendColumnType\":\"TEMPLATE\"}]\n" +
                "1591055866312200193\t[{\"columnAlis\":\"advice\",\"templateId\":\"1557962783618682882\",\"content\":\"【模型告警】监测到内网IP【${srcAddress}】扫描主机【${destAddress}】达到${eventCount_sum}次，请确认发起扫描的IP地址是否为授权行为，对来自内网的未授权扫描器IP及时隔离处置，并及时排查是否失陷。\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"sla\",\"templateId\":\"1558005591847129090\",\"content\":\"if(JSONExtractInt(__src_detail_info, 'asset_sla') = 0, 2, toInt32(ceil(2 * 0.4 + JSONExtractInt(__src_detail_info, 'asset_sla') * 0.6)))\",\"extendColumnType\":\"EXPRESSION\"},{\"columnAlis\":\"new_alarm_name\",\"templateId\":\"\",\"content\":\"模型-内网主机扫描单个内网目标\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"new_category\",\"templateId\":\"\",\"content\":\"内网扫描\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"rule_sla\",\"content\":\"2\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"rule_sla_weight\",\"content\":\"0.4\",\"extendColumnType\":\"TEMPLATE\"}]\n" +
                "1591055988232228865\t[{\"columnAlis\":\"advice\",\"templateId\":\"1557962783618682882\",\"content\":\"【模型告警】监测到外网IP【${srcAddress}】扫描主机【${destAddress}】达到${eventCount_sum}次，请确认发起扫描的IP地址是否为授权行为，对来自外网的未授权扫描器IP及时封禁处置。\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"sla\",\"templateId\":\"1558005591847129090\",\"content\":\"if(JSONExtractInt(__src_detail_info, 'asset_sla') = 0, 2, toInt32(ceil(2 * 0.4 + JSONExtractInt(__src_detail_info, 'asset_sla') * 0.6)))\",\"extendColumnType\":\"EXPRESSION\"},{\"columnAlis\":\"new_alarm_name\",\"templateId\":\"\",\"content\":\"模型-外到内扫描单目标\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"new_category\",\"templateId\":\"\",\"content\":\"外网扫描\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"rule_sla\",\"content\":\"2\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"rule_sla_weight\",\"content\":\"0.4\",\"extendColumnType\":\"TEMPLATE\"}]\n" +
                "1595006938982584321\t[{\"columnAlis\":\"advice\",\"templateId\":\"1557962783618682882\",\"content\":\"【模型告警】监测到外网IP【${srcAddress}】扫描主机【${destAddress}】达到${eventCount_sum}次，请确认发起扫描的IP地址是否为授权行为，对来自外网的未授权扫描器IP及时封禁处置。\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"sla\",\"templateId\":\"1558005591847129090\",\"content\":\"if(JSONExtractInt(__src_detail_info, 'asset_sla') = 0, 3, toInt32(ceil(3 * 0.4 + JSONExtractInt(__src_detail_info, 'asset_sla') * 0.6)))\",\"extendColumnType\":\"EXPRESSION\"},{\"columnAlis\":\"new_alarm_name\",\"templateId\":\"\",\"content\":\"模型-外到内扫描单目标\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"new_category\",\"templateId\":\"\",\"content\":\"外网扫描\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"rule_sla\",\"content\":\"3\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"rule_sla_weight\",\"content\":\"0.4\",\"extendColumnType\":\"TEMPLATE\"}]\n" +
                "1595008520801423361\t[{\"columnAlis\":\"advice\",\"templateId\":\"1557962783618682882\",\"content\":\"【模型告警】监测到内网IP【${srcAddress}】扫描主机【${destAddress}】达到${eventCount_sum}次，请确认发起扫描的IP地址是否为授权行为，对来自内网的未授权扫描器IP及时隔离处置，并及时排查是否失陷。\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"sla\",\"templateId\":\"1558005591847129090\",\"content\":\"if(JSONExtractInt(__src_detail_info, 'asset_sla') = 0, 3, toInt32(ceil(3 * 0.4 + JSONExtractInt(__src_detail_info, 'asset_sla') * 0.6)))\",\"extendColumnType\":\"EXPRESSION\"},{\"columnAlis\":\"new_alarm_name\",\"templateId\":\"\",\"content\":\"模型-主机对外部单个目标扫描\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"new_threat_severity\",\"templateId\":\"\",\"content\":\"高危\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"new_category\",\"templateId\":\"\",\"content\":\"主机对外扫描\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"rule_sla\",\"content\":\"3\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"rule_sla_weight\",\"content\":\"0.4\",\"extendColumnType\":\"TEMPLATE\"}]\n" +
                "1595238742746402817\t[{\"columnAlis\":\"advice\",\"templateId\":\"1557962783618682882\",\"content\":\"【模型告警】监测到内网IP【${srcAddress}】扫描主机【${destAddress}】达到${eventCount_sum}次，请确认发起扫描的IP地址是否为授权行为，对来自内网的未授权扫描器IP及时隔离处置，并及时排查是否失陷。\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"sla\",\"templateId\":\"1558005591847129090\",\"content\":\"if(JSONExtractInt(__src_detail_info, 'asset_sla') = 0, 3, toInt32(ceil(3 * 0.4 + JSONExtractInt(__src_detail_info, 'asset_sla') * 0.6)))\",\"extendColumnType\":\"EXPRESSION\"},{\"columnAlis\":\"new_alarm_name\",\"templateId\":\"\",\"content\":\"模型-内网主机扫描单个内网目标\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"new_category\",\"templateId\":\"\",\"content\":\"内网扫描\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"rule_sla\",\"content\":\"3\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"rule_sla_weight\",\"content\":\"0.4\",\"extendColumnType\":\"TEMPLATE\"}]\n" +
                "1595239043922595842\t[{\"columnAlis\":\"advice\",\"templateId\":\"1557962783618682882\",\"content\":\"【模型告警】监测到内网IP【${srcAddress}】扫描主机【${destAddress}】达到${eventCount_sum}次，请确认发起扫描的IP地址是否为授权行为，对来自内网的未授权扫描器IP及时隔离处置，并及时排查是否失陷。\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"sla\",\"templateId\":\"1558005591847129090\",\"content\":\"if(JSONExtractInt(__src_detail_info, 'asset_sla') = 0, 3, toInt32(ceil(3 * 0.4 + JSONExtractInt(__src_detail_info, 'asset_sla') * 0.6)))\",\"extendColumnType\":\"EXPRESSION\"},{\"columnAlis\":\"new_alarm_name\",\"templateId\":\"\",\"content\":\"模型-主机对外部单个目标扫描\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"new_threat_severity\",\"templateId\":\"\",\"content\":\"高危\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"new_category\",\"templateId\":\"\",\"content\":\"主机对外扫描\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"rule_sla\",\"content\":\"3\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"rule_sla_weight\",\"content\":\"0.4\",\"extendColumnType\":\"TEMPLATE\"}]\n" +
                "1595239406671171585\t[{\"columnAlis\":\"advice\",\"templateId\":\"1557962783618682882\",\"content\":\"【模型告警】监测到外网IP【${srcAddress}】扫描主机【${destAddress}】达到${eventCount_sum}次，请确认发起扫描的IP地址是否为授权行为，对来自外网的未授权扫描器IP及时封禁处置。\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"sla\",\"templateId\":\"1558005591847129090\",\"content\":\"if(JSONExtractInt(__src_detail_info, 'asset_sla') = 0, 3, toInt32(ceil(3 * 0.4 + JSONExtractInt(__src_detail_info, 'asset_sla') * 0.6)))\",\"extendColumnType\":\"EXPRESSION\"},{\"columnAlis\":\"new_alarm_name\",\"templateId\":\"\",\"content\":\"模型-外到内扫描单目标\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"new_category\",\"templateId\":\"\",\"content\":\"外网扫描\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"rule_sla\",\"content\":\"3\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"rule_sla_weight\",\"content\":\"0.4\",\"extendColumnType\":\"TEMPLATE\"}]\n" +
                "1597428379728416770\t[{\"columnAlis\":\"advice\",\"templateId\":\"1557962783618682882\",\"content\":\"【模型告警】监测到内网IP【${srcAddress}】扫描主机【${destAddress}】达到${eventCount_sum}次，请确认发起扫描的IP地址是否为授权行为，对来自内网的未授权扫描器IP及时隔离处置，并及时排查是否失陷。\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"sla\",\"templateId\":\"1558005591847129090\",\"content\":\"if(JSONExtractInt(__src_detail_info, 'asset_sla') = 0, 2, toInt32(ceil(3 * 0.4 + JSONExtractInt(__src_detail_info, 'asset_sla') * 0.6)))\",\"extendColumnType\":\"EXPRESSION\"},{\"columnAlis\":\"new_alarm_name\",\"templateId\":\"\",\"content\":\"模型-内网主机扫描单个内网目标\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"new_category\",\"templateId\":\"\",\"content\":\"内网扫描\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"rule_sla\",\"content\":\"3\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"rule_sla_weight\",\"content\":\"0.4\",\"extendColumnType\":\"TEMPLATE\"}]\n" +
                "1597428647983517698\t[{\"columnAlis\":\"advice\",\"templateId\":\"1557962783618682882\",\"content\":\"【模型告警】监测到内网IP【${srcAddress}】扫描主机【${destAddress}】达到${eventCount_sum}次，请确认发起扫描的IP地址是否为授权行为，对来自内网的未授权扫描器IP及时隔离处置，并及时排查是否失陷。\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"sla\",\"templateId\":\"1558005591847129090\",\"content\":\"if(JSONExtractInt(__src_detail_info, 'asset_sla') = 0, 2, toInt32(ceil(3 * 0.4 + JSONExtractInt(__src_detail_info, 'asset_sla') * 0.6)))\",\"extendColumnType\":\"EXPRESSION\"},{\"columnAlis\":\"new_alarm_name\",\"templateId\":\"\",\"content\":\"模型-主机对外部单个目标扫描\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"new_threat_severity\",\"templateId\":\"\",\"content\":\"高危\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"new_category\",\"templateId\":\"\",\"content\":\"主机对外扫描\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"rule_sla\",\"content\":\"3\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"rule_sla_weight\",\"content\":\"0.4\",\"extendColumnType\":\"TEMPLATE\"}]\n" +
                "1597428956092895233\t[{\"columnAlis\":\"advice\",\"templateId\":\"1557962783618682882\",\"content\":\"【模型告警】监测到外网IP【${srcAddress}】扫描主机【${destAddress}】达到${eventCount_sum}次，请确认发起扫描的IP地址是否为授权行为，对来自外网的未授权扫描器IP及时封禁处置。\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"sla\",\"templateId\":\"1558005591847129090\",\"content\":\"if(JSONExtractInt(__src_detail_info, 'asset_sla') = 0, 2, toInt32(ceil(3 * 0.4 + JSONExtractInt(__src_detail_info, 'asset_sla') * 0.6)))\",\"extendColumnType\":\"EXPRESSION\"},{\"columnAlis\":\"new_alarm_name\",\"templateId\":\"\",\"content\":\"模型-外到内扫描单目标\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"new_category\",\"templateId\":\"\",\"content\":\"外网扫描\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"rule_sla\",\"content\":\"3\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"rule_sla_weight\",\"content\":\"0.4\",\"extendColumnType\":\"TEMPLATE\"}]\n" +
                "1649972204763791362\t[{\"columnAlis\":\"advice\",\"templateId\":\"1557962783618682882\",\"content\":\"【模型告警】监测到内网IP【${srcAddress}】扫描主机【${destAddress}】达到${eventCount_sum}次，请确认发起扫描的IP地址是否为授权行为，对来自内网的未授权扫描器IP及时隔离处置，并及时排查是否失陷。\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"sla\",\"templateId\":\"1558005591847129090\",\"content\":\"if(JSONExtractInt(__src_detail_info, 'asset_sla') = 0, 3, toInt32(ceil(3 * 0.4 + JSONExtractInt(__src_detail_info, 'asset_sla') * 0.6)))\",\"extendColumnType\":\"EXPRESSION\"},{\"columnAlis\":\"new_alarm_name\",\"templateId\":\"\",\"content\":\"模型-内网主机扫描单个内网目标\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"new_category\",\"templateId\":\"\",\"content\":\"内网扫描\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"rule_sla\",\"content\":\"3\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"rule_sla_weight\",\"content\":\"0.4\",\"extendColumnType\":\"TEMPLATE\"}]\n" +
                "1654000565798486017\t[{\"columnAlis\":\"advice\",\"templateId\":\"1557962783618682882\",\"content\":\"【模型告警】监测到外网IP【${srcAddress}】扫描主机【${destAddress}】达到${eventCount_sum}次，请确认发起扫描的IP地址是否为授权行为，对来自外网的未授权扫描器IP及时封禁处置。\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"sla\",\"templateId\":\"1558005591847129090\",\"content\":\"if(JSONExtractInt(__src_detail_info, 'asset_sla') = 0, 3, toInt32(ceil(3 * 0.4 + JSONExtractInt(__src_detail_info, 'asset_sla') * 0.6)))\",\"extendColumnType\":\"EXPRESSION\"},{\"columnAlis\":\"new_alarm_name\",\"templateId\":\"\",\"content\":\"模型-外到内扫描单目标\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"new_category\",\"templateId\":\"\",\"content\":\"外网扫描\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"rule_sla\",\"content\":\"3\",\"extendColumnType\":\"TEMPLATE\"},{\"columnAlis\":\"rule_sla_weight\",\"content\":\"0.4\",\"extendColumnType\":\"TEMPLATE\"}]";
        Arrays.stream(data.split("\n")).forEach(o -> {
            String[] split = o.split("\t");
            JSONArray jsonArray = JSON.parseArray(split[1]);
            for (int i = 0; i < jsonArray.size(); i++) {
                JSONObject jsonObject = jsonArray.getJSONObject(i);
                if ("sla".equals(jsonObject.getString("columnAlis"))) {
                    String content = jsonObject.getString("content");
                    String key = "JSONExtractInt(__src_detail_info, 'asset_sla')";
                    assert content.contains(key);
                    String sla = content.substring(content.indexOf("toInt32"), content.length() - 1);
                    jsonObject.put("content", String.format("if(%s = 3, %s, %s)", key, sla.replace("ceil", "round"), sla));
                }
            }
            String json = jsonArray.toJSONString();
            log.info(String.format("update analysis_model_table set extend_column='%s' where id='%s';", json.replace("'", "\\'"), split[0]));
        });
    }
}
